# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name auth.aboutdevops.my.id;
    include /etc/nginx/snippets/redirect-https.conf;
}

# HTTPS - auth.aboutdevops.my.id -> Authelia portal
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name auth.aboutdevops.my.id;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/security-headers.conf;

    resolver 127.0.0.11 valid=5s;

    location / {
        set $upstream http://authelia:9091;
        proxy_pass $upstream;
        include /etc/nginx/snippets/proxy-params.conf;
    }
}
