# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name core.aboutdevops.my.id;
    include /etc/nginx/snippets/redirect-https.conf;
}

# HTTPS - core.aboutdevops.my.id
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name core.aboutdevops.my.id;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location / {
        proxy_pass http://backend:8080;
        include /etc/nginx/snippets/proxy-params.conf;
    }
}
