# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name docs-private.aboutdevops.my.id;
    include /etc/nginx/snippets/redirect-https.conf;
}

# HTTPS - docs-private.aboutdevops.my.id -> Docusaurus (gated by Authelia)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name docs-private.aboutdevops.my.id;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/security-headers.conf;
    include /etc/nginx/snippets/authelia-authz-location.conf;

    location / {
        include /etc/nginx/snippets/authelia-authreq.conf;
        proxy_pass http://docs-private:3000;
        include /etc/nginx/snippets/proxy-params.conf;
    }
}
