# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name harbor.aboutdevops.my.id;
    include /etc/nginx/snippets/redirect-https.conf;
}

# HTTPS - harbor.aboutdevops.my.id -> Harbor (own login, no Authelia)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name harbor.aboutdevops.my.id;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/security-headers.conf;

    # Matikan limit max body size untuk docker push (layer image yang besar)
    client_max_body_size 0;

    # Matikan request/response buffering untuk streaming layer docker
    proxy_request_buffering off;
    proxy_buffering off;

    resolver 127.0.0.11 valid=5s;

    location / {
        # Harbor v2.15.0 (official installer) - listens on host port 8089
        set $upstream http://127.0.0.1:8089;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        include /etc/nginx/snippets/proxy-params.conf;
    }
}
