# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name metrics.aboutdevops.my.id;
    include /etc/nginx/snippets/redirect-https.conf;
}

# HTTPS - metrics.aboutdevops.my.id (OTel Prometheus metrics Infisical)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name metrics.aboutdevops.my.id;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/security-headers.conf;

    auth_basic "Infisical Metrics";
    auth_basic_user_file /etc/nginx/htpasswd/infisical-metrics.htpasswd;

    resolver 127.0.0.11 valid=5s;

    location = / {
        return 301 /metrics;
    }

    location / {
        set $upstream http://infisical-backend:9464;
        proxy_pass $upstream;
        include /etc/nginx/snippets/proxy-params.conf;
    }
}
